# Generated by Django 3.0 on 2020-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_eq_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='eq_model',
            name='pq_curve_points',
            field=models.CharField(blank=True, default='0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,;0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,', max_length=150),
        ),
    ]
