# Generated by Django 3.0 on 2020-04-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20200421_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eq_mark',
            old_name='mark',
            new_name='eq_mark',
        ),
    ]
