# Generated by Django 3.0 on 2020-04-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20200421_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eq_mark',
            name='pq_curve_points',
            field=models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,;0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,', max_length=150),
        ),
    ]
