# Generated by Django 3.0 on 2020-05-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20200421_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='eq_mark',
            name='efficency_curve_points',
            field=models.CharField(blank=True, default='0.000.000.000.000.000.000.000.000.000.000.000.000.000.000.00;0.000.000.000.000.000.000.000.000.000.000.000.000.000.000.00', max_length=150),
        ),
        migrations.AddField(
            model_name='eq_mark',
            name='npsh_curve_points',
            field=models.CharField(blank=True, default='0.000.000.000.000.000.000.000.000.000.000.000.000.000.000.00;0.000.000.000.000.000.000.000.000.000.000.000.000.000.000.00', max_length=150),
        ),
        migrations.AddField(
            model_name='eq_mark',
            name='p2_curve_points',
            field=models.CharField(blank=True, default='0.000.000.000.000.000.000.000.000.000.000.000.000.000.000.00;0.000.000.000.000.000.000.000.000.000.000.000.000.000.000.00', max_length=150),
        ),
        migrations.AlterField(
            model_name='eq_mark',
            name='pq_curve_points',
            field=models.CharField(blank=True, default='0.000.000.000.000.000.000.000.000.000.000.000.000.000.000.00;0.000.000.000.000.000.000.000.000.000.000.000.000.000.000.00', max_length=150),
        ),
    ]
