# Generated by Django 3.0 on 2020-05-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20200502_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eq_mark',
            name='pq_curve_points',
        ),
        migrations.AddField(
            model_name='eq_mark',
            name='p_curve_points',
            field=models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150),
        ),
        migrations.AddField(
            model_name='eq_mark',
            name='q_curve_points',
            field=models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150),
        ),
        migrations.AlterField(
            model_name='eq_mark',
            name='efficency_curve_points',
            field=models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150),
        ),
        migrations.AlterField(
            model_name='eq_mark',
            name='npsh_curve_points',
            field=models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150),
        ),
        migrations.AlterField(
            model_name='eq_mark',
            name='p2_curve_points',
            field=models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150),
        ),
    ]
