# Generated by Django 3.0 on 2020-05-02 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20200502_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eq_mark',
            old_name='p_curve_points',
            new_name='h_curve_points',
        ),
    ]
