# Generated by Django 3.0 on 2020-05-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20200502_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eq_mark',
            old_name='efficency_curve_points',
            new_name='efficiency_curve_points',
        ),
    ]
